include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for Harbor File
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat

PKG_NAME:=luci-app-harbor-file

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
