name: Sync upstream

on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
      - '.gitignore'
      - '.github/diy/**'
      - '.github/scripts/**'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
    inputs:
      ssh:
        description: Enable SSH debugging
        type: boolean
        default: false
  watch:
    types: started
  repository_dispatch:

permissions:
  actions: write
  contents: write

concurrency:
  group: sync-upstream-${{ github.repository }}
  cancel-in-progress: false

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id || github.event.sender.id == '119362912'
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        token: ${{ github.token }}

    - name: Set git identity
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

    - name: Sync upstream
      run: bash .github/scripts/sync-upstream.sh

    - name: Prepare packages
      run: bash .github/scripts/prepare-packages.sh

    - name: SSH connection to Actions
      uses: kiddin9/debugger-action@master
      if: github.event.inputs.ssh == 'true'

    - name: Apply patches
      run: bash .github/scripts/apply-patches.sh

    - name: Modify
      env:
        GH_TOKEN: ${{ github.token }}
      run: bash .github/scripts/modify-packages.sh

    - name: Check package conflicts
      run: bash .github/scripts/check-package-conflicts.sh

    - name: Commit and push
      run: bash .github/scripts/commit-changes.sh

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
